@baseUrl = http://localhost:3333 
@apiKey = K3q1IssTe1qIEgfTqFvVmqB6Knzeqll9EB76bhyyM6jf3C96siq9Tr7Cf16EPZ08 

# @name create_broth
POST {{baseUrl}}/broths
Content-Type: application/json
x-api-key: {{apiKey}}

{
  "name": "Tonkotsu",
  "description": "Breaded and fried pork fillet.",
  "price": 10,
  "imageActiveId": "3ebe8944-1f98-46f3-8811-0da7588f2d00",
  "imageInactiveId": "37505e8c-f3f0-4c7c-88e3-9d6cb91a7a74"
}

###

# @name list_broth
GET {{baseUrl}}/broths
Content-Type: application/json
x-api-key: {{apiKey}}

###

# @name create_protein
POST {{baseUrl}}/proteins
Content-Type: application/json
x-api-key: {{apiKey}}

{
  "name": "Chasu",
  "description": "A sliced flavourful pork meat with a selection of season vegetables.",
  "price": 10,
  "imageActiveId": "f6bd097c-126e-479d-908f-e3f7c0c0826e",
  "imageInactiveId": "453c15b2-c02a-4bb0-8352-7dd0adbd9ff0"
}

###

# @name upload_image
POST {{baseUrl}}/images
Content-Type: multipart/form-data; boundary=boundary123
x-api-key: {{apiKey}}

--boundary123
Content-Disposition: form-data; name="file"; filename="sample-upload.svg"
Content-Type: image/svg+xml

< ./test/e2e/sample-upload.svg
--boundary123--