version: '3.8'

services:
  postgres:
    container_name: ramen-go-api-pg
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: ramen-go
      PGDATA: /data/postgres
    volumes:  
      - ./data/pg:/data/postgres